server:
  port: 8080
  servlet:
    context-path: /todo
  error:
    include-binding-errors: ALWAYS
    include-message: ALWAYS

spring:
  application:
    name: TODO App
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: user
    password: password
    driver-class-name: java.sql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update